### ISSUE TITLE
[Suggestion] Custom Duration

### ISSUE THREAD

**Issue by nyxs** [nitaybz/homebridge-switcher-platform#14]
Hey.
I started using your components and everything's good, but I was wondering if you can add an option to have custom duration. Let the user add 3 custom durations, for example.

**Comment by nitaybz** [comment]
It's a bug in iOS 14.
When you choose valve as accessory type you should have all the options for duration.... unfortunately the bug is showing only your current and another 2 weird options which I can't control or change.
You can verify me by opening the Home app from a Mac and see all the options.

I hope Apple will solve it soon...

**Comment by nyxs** [comment]
I have only 5 or 10 minutes, both on my iPhone and my mac.
Do you know what should be there usually?

**Comment by nitaybz** [comment]
Try the Eve app until Apple will solve this issue

**Comment by dmatik** [comment]
Same here.
In Eve app it works fine.

**Comment by dmatik** [comment]
Can you maybe set it to 4 constant values 15/30/45/60 as it is in original Switcher app, as a workaround, temporary, until Apple fixes this? Is that possible?

**Comment by millerhaim** [comment]
I want to joins @dmatik request.
Until Apple will fix this issue, can you please change the value to 15/30/45/60 as manually default?

Thanks.

**Comment by nyxs** [comment]
@millerhaim and everybody who wants this, you can use the app Eve. They implemented it by themselves. You can choose there 30 mins or whatever you want. Then you'll be able to see it in the Home app.

**Comment by nitaybz** [comment]
so first of all, I can't set those values you requested... as i've said, it's apple's bug and cannot be modified in the Home app.
the good news is that in the latest release v4 of the plugin, you can create custom switches to turn on the boiler for X minutes. checkout the readme for more details

**Comment by millerhaim** [comment]
@nitaybz Thanks, will check it out!
