### ISSUE TITLE
Support Switcher Runner

### ISSUE THREAD

**Issue by erlichmen** [nitaybz/homebridge-switcher-platform#15]
I have three units of the new [Switcher Runner,](https://switcher.co.il/%D7%9E%D7%95%D7%A6%D7%A8/switcher-runner/) any help you need I can provide.

**Comment by nitaybz** [comment]
@erlichmen i saw you are a developer... feel free to create PR for the switcher-js2 library or any switcher supported library, there are plenty in python if you prefer.
Once you've done that in will be able to replicate the code.

**Comment by nitaybz** [comment]
already supported
