### ISSUE TITLE
Request failed - during plug-in installation

### ISSUE THREAD

**Issue by DanSuSDPB** [nitaybz/homebridge-switcher-platform#17]
Im trying to install the plug-in(Switcher-platform V4.0.4)from the Homemanager(V3.3.5) app with the following error message. 

![image](https://user-images.githubusercontent.com/68084142/113470941-c30bc880-9461-11eb-974c-ffe33299d356.png)

Short log from the app(I can attach the entire file if needed) 

![image](https://user-images.githubusercontent.com/68084142/113470964-eafb2c00-9461-11eb-8f84-54d18dfd7e88.png)

Thanks in advance :)

**Comment by nitaybz** [comment]
still happening?

**Comment by DanSuSDPB** [comment]
Hi Nitay 

No, I listened to you :) 
Moved from Hoobs to Homebridge and now I don't have any issues. 

Thanks 🙏🏻
