### ISSUE TITLE
Any Clue how to hide Switcher logs in HomeBridge plugin

### ISSUE THREAD

**Issue by albilia** [nitaybz/homebridge-switcher-platform#22]
Hi @nitaybz 
I can't find any possible way to hide Switcher logs in HomeBridge plugin. 
I would greatly appreciate getting a trick that could do the job. Thanks in advance  : )

**Comment by nitaybz** [comment]
hidden in the new version when debug logs is disabled

**Comment by nitaybz** [comment]
Only set commands will be printed

**Comment by albilia** [comment]
thanks a lot ya gever  : )
