### ISSUE TITLE
Switcher breeze

### ISSUE THREAD

**Issue by NirLevy98** [nitaybz/homebridge-switcher-platform#31]
Hello,
The switcher breeze is always connected and disconnected when I try to control it from home kit after every command it disconnects and connect after serval minutes. 
At the logs area every minute it's print: ![image](https://user-images.githubusercontent.com/7195780/177881785-1adc5021-33fd-4fb5-9421-3f1b685c7616.jpeg)

**Comment by nitaybz** [comment]
Please try the latest version 4.2.15

**Comment by NirLevy98** [comment]
I updated to the newest version and now I have different issue
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/7195780/178752613-f869db8f-1356-4bda-93dc-9841f91c63d8.png">

**Comment by nitaybz** [comment]
should be resolved now, please update
