### ISSUE TITLE
Does this plugin also supports Switcher Smart Plug?

### ISSUE THREAD

**Issue by edento** [nitaybz/homebridge-switcher-platform#36]
On the switcher website they refer to this plugin, but in this plugin supported devices it's not listed.
any idea? I haven't purchased it yet so I cant just test it.

Thanks

**Comment by nitaybz** [comment]
Yes it is supported

**Comment by guyluz11** [comment]
I think this issue can be closed.

I am actually intending to also buy smart plugs and test them, the support for smart plugs is waiting in the readme
