### ISSUE TITLE
Creating siri shortcut that turning the boiler to X minutets

### ISSUE THREAD

**Issue by Idomo** [nitaybz/homebridge-switcher-platform#37]
Hi @nitaybz, first thing, thank you for creating this plugin (wish I was find it earlier).

I'm into making the usage of the HomeKit more automated by creating a shortcut that will check the boiler temperature and allow me to turn on the boiler for X minuets in certain conditions.

So far I was able to make it all except of the part of the waiting between the "Turn on" and the "Turn off";
With the "valve" type I couldn't add the device to any automation even tho it supporting custom timer (it doesn't appears in the devices' list), so I had to use the "switch" type, but the "Wait" function doesn't work for more than a few seconds and I couldn't find any other way to set a timer for a "switch"...

I'd like to know if you have any suggestion to how to implement this action (turn on with a timer from a given time) or if there is any possibility to add support for this in the plugin itself.

Thanks,
Ido.

**Comment by nitaybz** [comment]
I've created the Custom timers specifically for that:
https://github.com/nitaybz/homebridge-switcher-platform#custom-timers

**Comment by Idomo** [comment]
@nitaybz, I have tested this, but it didn't provide me with any "virtual switch" as described in the docs.
You may tell me if there is anything I haven't configured correctly:
```json
 "platforms": [
  {
    "name": "Switcher Platform",
    "debug": false,
    "secondsToRemove": 0,
    "devices": [
      {
        "identifier": "Switcher V4 XXX",
        "accessoryType": "switch"
      }
    ],
    "customTimers": [
      {
        "identifier": "Switcher V4 XXX",
        "shutdownMinutes": 30
      },
      {
        "identifier": "Switcher V4 XXX",
        "shutdownMinutes": 90
      }
    ],
      "_bridge": {
        "username": "...",
        "port": 123
      },
    "platform": "SwitcherPlatform"
  }
]
```
*I've tried also removing the `"accessoryType"` setting as you've mentioned it's available only for boiler, but same result - nothing.
