### ISSUE TITLE
Accessory only shows current state but can't control it

### ISSUE THREAD

**Issue by liormoyal** [nitaybz/homebridge-switcher-platform#40]
When trying to change the state it does not respond (From Homebridge or HomeKit).
Only shows the current state of the switch (Switcher Mini).

**Comment by nir-f** [comment]
Same here
@nitaybz I have the same issue as I opened new ticket but its similar case I guess

**Comment by nitaybz** [comment]
From the switcher app settings change to local and turn on and off from there... after a little while I should work again in HomeKit and you can cancel the local mode

**Comment by nir-f** [comment]
Also, need to request from switcher support to upgrade FW version.
Afterwards the "local" configuration fix the problem.

Thanks!
