### ISSUE TITLE
Add manual configuration for devices not on the same subnet

### ISSUE THREAD

**Issue by orenhecht** [nitaybz/homebridge-switcher-platform#43]
A good security practice is to create a IoT network and add firewall rules to block traffic from that network to the internal LAN. This plugin auto-detect feature only works if the homebridge device is on the same network as the Switcher device.

Please add an option to manually specify the Switcher device IP address so it can communicate without auto-detect.

**Comment by nitaybz** [comment]
unfortunately this is not how the plugin works. The plugin get status updates by listening to a certain port on the network.
it gotta be on the same network.

closing since it's not gonna be implemented
