### ISSUE TITLE
Add new light switches

### ISSUE THREAD

**Issue by RavidCo** [nitaybz/homebridge-switcher-platform#45]
Hi, recently Switcher added new light switches, I would appreciate it if you could add them that will also support homekit

**Comment by gavrie** [comment]
I think this is a duplicate of #42

**Comment by RavidCo** [comment]
You're right, now I notice. 

Can you guess when the plugin will be supported?

**Comment by gavrie** [comment]
I don't know how much this project is being maintained, so no idea... I may give it a try myself, but the problem is finding the time 😄

**Comment by RavidCo** [comment]
Oh sorry, I thought you were Nitay 
I assume he will find the time to sit on it, 

regarding taking on the project, I understand less about it and therefore cannot express an opinion on the matter

**Comment by nitaybz** [comment]
working on it... closing as this is duplicate of #42
