### ISSUE TITLE
Any plans to create home-assistant version of this awesome plugin?

### ISSUE THREAD

**Issue by dudutwizer** [nitaybz/homebridge-switcher-platform#48]
I am literally running Homebridge just for this plugin, and I would like to shut it down because I find Home Assistant much better. The problem is that Home Assistant doesn't have support for Switcher. There is one plugin that can control only the blinds and nothing more.

**Comment by nitaybz** [comment]
I'm using the home assistant integration on another machine, it seems quite sufficient to me, supporting the same accessories as this one.
closing this issue as I'm not gonna develop for home assistant as well
